name: WakaTime Readme

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: false
          SHOW_EDITORS: false
          SHOW_PROJECTS: false
          SHOW_TIMEZONE: false
          SHOW_COMMIT: false
          SHOW_PROFILE_VIEWS: false
          SHOW_LANGUAGE: true
          SHOW_TOTAL_CODE_TIME: true
